import {StyleSheet, Dimensions} from 'react-native';
import {COLORS} from '@/themes';

const {width, height} = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.WHITE,
  },
  toolbar: {
    display: 'flex',
    paddingTop: 30,
    paddingBottom: 50,
    paddingHorizontal: 15,
    backgroundColor: COLORS.WARNING,
  },
  form: {
    marginTop: -20,
    backgroundColor: COLORS.WHITE,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    paddingVertical: 40,
    paddingHorizontal: 30,
  },
  title: {
    textAlign: 'center',
    fontFamily: 'Sarala-Bold',
    fontSize: 24,
    color: COLORS.DARK,
    marginBottom: 30,
  },
  description: {
    fontFamily: 'Sarala-Regular',
    fontSize: 15,
    color: COLORS.SECONDARY,
    marginBottom: 35,
    textAlign: 'center',
  },
  formGroup: {
    marginBottom: 30,
    position: 'relative',
  },
  label: {
    fontFamily: 'Sarala-Regular',
    fontSize: 15,
    color: COLORS.SECONDARY,
  },
  textField: {
    height: 40,
    fontFamily: 'Sarala-Regular',
    fontSize: 15,
    borderBottomWidth: 1,
    borderColor: COLORS.SECONDARY,
    color: COLORS.DARK,
  },
  statusShowPassword: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: 40,
    height: 40,
    position: 'absolute',
    bottom: 0,
    right: 0,
    zIndex: 2,
    opacity: 0.5,
  },
  forgotPassword: {
    textAlign: 'right',
    fontFamily: 'Sarala-Regular',
    fontSize: 15,
    marginBottom: 50,
    color: COLORS.DARK,
  },
  reset: {
    height: 44,
    borderRadius: 8,
    backgroundColor: COLORS.WARNING,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  resetText: {
    fontFamily: 'Sarala-Bold',
    fontSize: 17,
    color: COLORS.WHITE,
  },
  centeredView: {
    width,
    height,
    position: 'relative',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalBg: {
    width,
    height,
    position: 'absolute',
    top: 0,
    left: 0,
    backgroundColor: '#000',
    opacity: 0.45,
  },
  modalView: {
    backgroundColor: '#FFF',
    width: 345,
    height: 400,
    borderRadius: 20,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalTitle: {
    fontFamily: 'Sarala-Regular',
    fontSize: 32,
    marginTop: 40,
    marginBottom: 20,
    textAlign: 'center',
    color: COLORS.WARNING,
  },
  modalContent: {
    fontFamily: 'Sarala-Regular',
    fontSize: 15,
    textAlign: 'center',
    color: COLORS.SECONDARY,
  },
});
